import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  BackGroundPhoto: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "flex-end",
  },
  containerLogin: {
    paddingTop: 32,
    paddingBottom: 111,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    marginTop: "auto",
  },
  containerRegistration: {
    paddingTop: 92,
    paddingBottom: 45,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    marginTop: "auto",
  },
  title: {
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
    letterSpacing: 0.01,
    marginBottom: 33,
    color: "#212121",
  },
  input: {
    height: 50,
    padding: 16,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 16,
  },
  lastInput: {
    marginBottom: 43,
  },
  buttonMain: {
    height: 50,
    padding: 16,
    borderRadius: 100,
    backgroundColor: "#ff6c00",
    marginBottom: 16,
  },
  buttonMainText: {
    fontFamily: "Roboto-Regular",
    textAlign: "center",
    fontSize: 16,
    lineHeight: 19,
    color: "#FFFFFF",
  },
  link: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    letterSpacing: 0.01,
    marginBottom: 30,
    color: "#1B4371",
  },
  showPassLogin: {
    position: "absolute",
    top: 16,
    right: 16,
    fontSize: 16,
    lineHeight: 19,
    color: "#1B4371",
  },
  photoPlaceholder: {
    position: "absolute",
    transform: [{ translateX: -50 }, { translateY: -60 }],
    left: "50%",
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
  },
  photoAdd: {
    position: "absolute",
    width: 25,
    height: 25,
    top: 81,
    left:107,
  },
   containerCreatePostScreen: {
    paddingTop: 32,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    marginTop: "auto",
  },
  cameraPlaceholder: {
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 8,
  },
  camera: {
    alignItems: "center",
    justifyContent: "center",
    height: 240,
  },
  cameraIcon: {
    // borderRadius: 40,
  },
  takenPhoto: {
    position: "absolute",
    width: 120,
    height: 80,
    borderRadius: 8,
    top: 5,
    right: 5,
    overflow: "hidden",
  },
  photoStatus: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#BDBDBD",
    marginBottom: 32,
  },
  photoNameInput: {
    height: 50,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  photoLocationInput: {
    height: 50,
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 32,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  photoInputText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
  },
  buttonDel: {
    width: 70,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F6F6F6",
    marginHorizontal:"auto",
    justifyContent: "center",
    alignItems:"center",
  },
  containerPostsScreen: {
    paddingTop: 32,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    marginBottom: 43,
  },
  userInfo: {
    marginBottom: 32,
  },
  postItem: {
    marginBottom: 32,
    gap: 8,
  },
  postItemName: {
    fontFamily: "Roboto-Medium",
    fontSize: 16,
    lineHeight: 19,
    color: "#212121",
  },
  postItemAttr: {
    width: "100%",
    flexDirection: "row",
    alignContent: "space-between",
    justifyContent: "space-between",
  },
  postItemLinkMsg: {
    alignItems: "center",
    flexDirection: "row",
  },
  postItemLinkLoc: {
    alignItems: "center",
    flexDirection: "row",
  },
  postItemLinkText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
  },
});

export default styles;